console.log("script.js loaded");

const loveNotes = [
    "Zahra, you are the sunshine of my life 🌞",
    "Every moment with you feels like a beautiful dream 💫",
    "You are my forever and always, Zahra ❤️",
    "Life is more colorful and joyful with you by my side 🎨",
    "You fill my heart with love and happiness 💖",
    "To the love of my life, Zahra – I cherish every moment with you 🥰",
    "I love you more than words can express, Zahra 💌",
    "Being with you makes everything feel perfect 🌹",
    "Thank you for being my partner, my friend, and my love 🌷",
    "Zahra, you complete me in every way possible 💍",
    "When I look at you, I see my forever ❤️",
    "Every love song I hear reminds me of you 🎶",
    "I am so grateful to have you in my life, Zahra 🌺",
    "You have the kindest heart, and I’m lucky to be the one you chose 💕",
    "I could search a lifetime and never find someone as wonderful as you 💖",
    "With you, I've found my home 🏠",
    "You inspire me to be a better person every day 🌟",
    "Our love story is my favorite one 💖",
    "I fall in love with you a little more every day 🌷",
    "No matter where life takes us, I’ll always love you endlessly 💞",
    "Thank you for making every day brighter 🌞",
    "In your eyes, I find my happiness 💫",
    "You are my soulmate, my best friend, my everything 💕",
    "Loving you is the best decision I’ve ever made 💖",
    "Forever isn't long enough when I'm with you 💍",
    "You are my heart's delight, and I am so proud to be yours 🌹",
    "Your smile lights up my world like nothing else 💖",
    "I’ll love you through every sunrise and every sunset 🌅",
    "Zahra, you are my heart, my world, my everything 💘",
    "Your love is my greatest blessing 🌈",
    "Every time I see you, I fall in love all over again ❤️",
    "With you, I have everything I need in life 💖",
    "Thank you for making every moment magical ✨",
    "Being yours forever is my dream come true 💍",
    "I am the luckiest person on earth because I have you 💖",
    "Loving you is my favorite thing to do ❤️",
    "You're the best part of my life, Zahra 🌸",
    "You make my heart smile 😊",
    "The world is more beautiful with you in it 🌷",
    "I’m so lucky to love you and to be loved by you 💕",
    "You are my muse, my love, my everything 🎨",
    "Every adventure with you feels like a fairytale 🌹",
    "Zahra, just seeing you makes my day infinitely better 💖",
    "You have a magic about you that fills my heart with joy ✨",
    "I could write a thousand love letters, but they’d never capture what you mean to me 💌",
    "I love you more deeply with each passing moment 💘",
    "With you, life is full of laughter, love, and endless happiness ❤️",
    "You are my one and only, Zahra, and I will cherish you forever 💍",
    "محبت تم سے اس قدر ہے کہ میں خود سے بھی بے خبر ہوں ❤️",
    "تمہیں پا کر میری دنیا مکمل ہو گئی، جیسے خزاں میں بہار آئی 💐",
    "زندگی کے ہر لمحے میں، میری دعا ہو تم 💞",
    "میرے دل کی ہر دھڑکن تمہارے نام سے ہے 💖",
    "محبت ہے تم سے، میری ہر سانس میں تم ہو 🌹",
    "In your love, I find peace and strength, a quiet calm in a chaotic world 🌌",
    "Tum meri zindagi ka wo haseen raaz ho jo kabhi na khatam ho 💍",
    "My heart is at home whenever I’m with you 🏠",
    "جب سے تم میری زندگی میں آئے ہو، ہر دن عید ہے 💕",
    "تمہاری مسکراہٹ میری زندگی کا سب سے قیمتی خزانہ ہے 😊",
    "تُو ہے تو زندگی حسین ہے، تُو نہ ہو تو کچھ بھی نہیں ❤️",
    "Meri har dua mein tum ho, meri har khushi ka sabab tum ho 💫",
    "You are the poetry in my heart, the melody in my soul 🎶",
    "زندگی تم سے ہے، اور تم میری زندگی ہو 🌹",
    "Tum meri zindagi ki woh kahani ho jo har din nayi lagti hai ❤️",
    "To be loved by you is a blessing I’ll cherish forever 💘",
    "Jab tum mere saath ho, duniya ki har cheez be-mani lagti hai 🌍",
    "You are my light, my guide, my love, my forever ❤️",
    "Every heartbeat whispers your name 💖",
    "Tum mere khawab ho, jo hamesha mere saath rahte hain 🌙",
    "If love is a journey, I’ll walk a million miles to be with you 💕",
    "Tere ishq mein meri har ghadi hai rangon se bhari ❤️",
    "Kabhi khamoshi se, kabhi baaton se tum mere dil mein basti ho 💖",
    "Tum jo paas ho, har din ek nayi kahani lagti hai 💕",
    "Your presence in my life is like a beautiful melody that never fades 🎶",
    "Tum ho toh har khushi, har raat suhani lagti hai 💫",
    "Pyar tumse hai, aur tum hi se meri har khushi hai 🌹",
    "You are my favorite place to go when my mind searches for peace 🌸",
    "Tere sang guzarta har lamha, zindagi ka khoobsurat safar lagta hai 🌈",
    "Aankhon mein tere sapne, aur dil mein teri yaadein hain ❤️",
    "Zindagi tere sang poori, tumhare bina adhoori lagti hai 💔",
    "Tum mere dil ka wo raaz ho, jo sirf tum samajh sakti ho 🌹",
    "Mujhe tum mein apna aashiyana mil gaya hai 🏠",
    "Jis pal mein tum ho, wo pal hamesha ke liye kaash ruk jaye 💫",
    "Tumhara saath mere liye ek khubsurat dua hai 💕",
    "You are the reason for my smile, the cause of my happiness 😊",
    "Tum ho toh har pal suhana, har raat chandni hai 🌙",
    "Tumse pyar karna mere dil ka sabse khoobsurat ehsaas hai ❤️",
    "Tumhari khushbu se mera dil aur yeh zindagi mahek uthti hai 🌸",
    "I love you not only for what you are, but for what I am when I’m with you 💕",
    "Tum wo sitare ho jo har raat mere dil ko chamkate hain ⭐",
    "In your love, I have found my forever, my always 💍",
    "Meri har dua tumse hai, aur tum mere liye ek khaas dua ho 🌹",
    "Tere saath zindagi ka safar khoobsurat aur mehfooz hai 🛤️",
    "Zahra, you are the sunshine of my life 🌞",
    "Every moment with you feels like a beautiful dream 💫",
    "You are my forever and always, Zahra ❤️",
    "Life is more colorful and joyful with you by my side 🎨",
    "I fall in love with you a little more every day 🌷",
    "With you, every day feels like a new beginning 🌅",
    "In your eyes, I find my peace and home 🏡",
    "Your laughter is my favorite melody 🎶",
    "You are my muse, my heart's poem 📝",
    "Every word you speak is like a beautiful verse 💖",
    "I am grateful for every moment spent with you ⏳",
    "You complete me in ways I never knew I needed 🧩",
    "Teri baaton mein kho jata hoon, tu hai meri zindagi ka haseen naghma 💞",
    "In your love, I found the meaning of eternity 🕰️",
    "Meri har subah tum se hai, aur har raat tumhare saath 🌌",
    "With you, love has become a journey of beautiful memories ✨",
    "You are the answer to every prayer I've whispered under the stars 🌠",
    "Tum ho mere khayalon ka shehar, meri har khushi ka aangan 💖",
    "I cherish every moment spent with you, my love 🌹",
    "In the world of chaos, you are my calm 🕊️",
    "You are the poetry my heart has been waiting to write ✍️",
    "Tumhare saath zindagi khoobsurat lagti hai 💞",
    "My heart beats only for you, my love 💓",
    "Every heartbeat whispers your name in silent reverence 💘",
    "Teri hasi meri jeet hai, tera gham meri haar 💔",
    "In your arms, I have found my sanctuary 🌹",
    "Tumhara saath mere sapnon ki manzil hai 🛤️",
    "No matter where life takes us, I'll always cherish you ❤️",
    "My love for you grows deeper with every sunrise 🌅",
    "Tum ho mere dil ka qareebi raaz 💌",
    "I’m lost in the beauty of your soul 🌌",
    "Zindagi ke har mod par tumhara intezaar karta hoon 💫",
    "I’m yours, today, tomorrow, and always 💍",
    "Every step with you feels like walking on clouds ☁️",
    "Tumhari khushboo meri zindagi ka hissa hai 💐",
    "In your love, I’ve found my forever 💞",
    "Your voice is the melody my heart dances to 🎶",
    "Aankhon mein tera aks hai, dil mein tera asar 💖",
    "Every word you speak is poetry to my soul 🌹",
    "You’re the only one I want by my side until the end of time ⏳",
    "Tum ho mere geeton ki dhun, mere sapnon ka rang 🌈",
    "Your love is my strength, my peace, my everything 💪",
    "Dil karta hai tere saath jeewan ka har pal bitaun 💫",
    "You are the light that brightens my darkest nights 🌌",
    "Teri yaadon se bhar gaya hai mera dil 💖",
    "Forever grateful for the love we share 💕",
    "Meri zindagi ka har rang sirf tum se hai 🌹",
    "Every moment without you feels incomplete 💔",
    "Tum mere khwabon ki hakikat ho, meri duniya ka qasida 💖",
    "I see my future in your eyes, clear and beautiful 🥰",
    "Tumhara saath meri zindagi ka sabse haseen tohfa hai 🎁",
    "With you, I’ve found my forever love 💞",
    "Tum mere dil ki awaaz ho, mere har armaan ki tasveer 💌",
    "Being with you is the most beautiful poetry I know 🌹",
    "You’re my heart’s favorite story, Zahra 📖",
    "Zahra, you are the sunshine of my life 🌞",
    "Every moment with you feels like a beautiful dream 💫",
    "You are my forever and always, Zahra ❤️",
    "Life is more colorful and joyful with you by my side 🎨",
    "I fall in love with you a little more every day 🌷",
    "With you, every day feels like a new beginning 🌅",
    "In your eyes, I find my peace and home 🏡",
    "Your laughter is my favorite melody 🎶",
    "You are my muse, my heart's poem 📝",
    "Every word you speak is like a beautiful verse 💖",
    "I am grateful for every moment spent with you ⏳",
    "You complete me in ways I never knew I needed 🧩",
    "In your love, I found the meaning of eternity 🕰️",
    "With you, love has become a journey of beautiful memories ✨",
    "You are the answer to every prayer I've whispered under the stars 🌠",
    "I cherish every moment spent with you, my love 🌹",
    "In the world of chaos, you are my calm 🕊️",
    "You are the poetry my heart has been waiting to write ✍️",
    "My heart beats only for you, my love 💓",
    "Every heartbeat whispers your name in silent reverence 💘",
    "In your arms, I have found my sanctuary 🌹",
    "No matter where life takes us, I'll always cherish you ❤️",
    "My love for you grows deeper with every sunrise 🌅",
    "I’m lost in the beauty of your soul 🌌",
    "I’m yours, today, tomorrow, and always 💍",
    "Every step with you feels like walking on clouds ☁️",
    "In your love, I’ve found my forever 💞",
    "Your voice is the melody my heart dances to 🎶",
    "Every word you speak is poetry to my soul 🌹",
    "You’re the only one I want by my side until the end of time ⏳",
    "Your love is my strength, my peace, my everything 💪",
    "You are the light that brightens my darkest nights 🌌",
    "Forever grateful for the love we share 💕",
    "With you, I’ve found my forever love 💞",
    "You are the one my heart calls home 🏠",
    "In your smile, I see my happiness 🌈",
    "Your love is the anchor that keeps me grounded ⚓️",
    "You are my heart’s quiet, unspoken wish 🌠",
    "In a world of noise, you are my sweet silence 🌿",
    "Every moment with you feels like a piece of heaven 🌌",
    "I love you more than words could ever describe 🖋️",
    "You are the missing piece that makes my heart whole 💖",
    "Together, we are poetry in motion ✍️",
    "With you, I've found the love I always dreamed of 🌹",
    "Every smile you give lights up my soul 🌟",
    "You are the dream I never want to wake up from 💤",
    "In your arms, I feel safe, cherished, and loved 💕",
    "You are the beat in my heart, the breath in my soul 💓",
    "With you, I feel like I am exactly where I belong 🏡",
    "You are my endless adventure, my infinite love 🌏",
    "I love you more than the stars in the sky ✨",
    "Your love is the song my heart sings 🎶",
    "With you, every second is a memory I want to keep forever ⏳",
    "You are my love story, written by the universe itself 🌌",
    "In your love, I've found my forever kind of happiness ❤️",
    "With you, every sunset is more beautiful 🌅",
    "Your love has painted my life in colors I never knew existed 🎨",
    "I choose you, and I will choose you, over and over again 💘",
    "Your love is the journey I want to take forever 🚀",
    "You are my once-in-a-lifetime kind of love 💍",
    "With you, my world feels complete and perfect 🌎",
    "You are the reason my heart races and my soul smiles 🌠",
    "In you, I have found my heart’s truest home 💖",
    "My love for you is timeless, boundless, and endless 🕰️",
    "You are the magic in my every day ✨",
    "With you, love feels like a never-ending story 📖",
    "My heart chose you, and it was the best decision I ever made 💗",
    "You are my best friend, my love, my everything ❤️",
    "Every kiss with you is a promise of forever 💋",
    "You are my favorite part of every day 🌄",
    "Your love is a treasure I hold close to my heart 💎",
    "With you, I’ve found a love I thought only existed in dreams 💫",
    "In your eyes, I see my forever 🌹",
    "Every part of me belongs to you 💑",
    "Loving you is the greatest adventure of my life 🌍",
    "I look at you and see all I ever wanted ❤️",
    "With you, I've found my forever and my always 💖",
    "Your love is my greatest joy and my deepest peace 🌌",
    "In you, I have found a love worth waiting a lifetime for ⏳",
    "You are my heart’s softest melody 🎶",
    "With you, every moment is filled with warmth and love ☀️",
    "Zahra, you are the sunshine of my life 🌞",
    "Every moment with you feels like a beautiful dream 💫",
    "You are my forever and always, Zahra ❤️",
    "Life is more colorful and joyful with you by my side 🎨",
    "I fall in love with you a little more every day 🌷",

    // English Love Poetry
    "In the quiet of my heart, your name is a gentle song, 🎶",
    "If love is a journey, you're my final destination and my endless path 🚶‍♂️❤️",
    "You are the stars I count when the night grows dark, my forever light 🌌",
    "Every word I speak of you is poetry in itself, crafted by the soul ✍️",
    "With every sunrise, my love for you blooms anew, like roses in the dawn 🌹",
    "In the garden of my dreams, you are the rarest flower 🌸",
    "Your love is the ink in my veins, writing stories in the silence of my heart 🖋️",
    "In your eyes, I see a thousand sunsets and the promise of forever 🌅",
    "Our love, a dance in the shadows, a whisper in the stars ✨",
    "With you, love feels like a gentle lullaby sung by the universe itself 🎶",

    "Like rivers to the ocean, my soul flows toward you endlessly 🌊",
    "You are the pages of my story, written with laughter and tears 📖",
    "In your presence, time fades, and only the moment remains ⏳",
    "My love for you is timeless, woven into the fabric of eternity ⏰",
    "I would cross a thousand lifetimes just to find you in each one 💫",
    "You are the verse I repeat, the line that completes my poetry ✍️",
    "In the language of my heart, your name is the only word that matters 💖",
    "Each heartbeat is a step closer to you, my love's endless journey 🛤️",
    "For every question of life, your love is the answer I've been seeking 🌠",
    "In the silence of my soul, your love is the melody that echoes ❤️",

    "If I could paint a picture of love, it would be the way you look at me 🎨",
    "You are the anchor that steadies my heart in life's stormiest seas ⚓️",
    "With every kiss, you write a story upon my lips 💋",
    "You are my heart’s hidden verse, a secret whispered to the stars 🌌",
    "If love were a language, you'd be every word I've ever known 📝",
    "With you, my world is poetry, each line written in light and laughter 🌄",
    "Your love is the lullaby that rocks my heart to peace 🌙",
    "In your warmth, my winter turns to spring, and all is reborn 🌼",
    "I loved you long before we met, in the corners of forgotten dreams 🌠",
    "You are my quiet strength, the peace beneath the chaos 💖",

    "In my heart's library, every book is written with your name 📚",
    "Your love is the brush that paints color into my soul 🎨",
    "With you, every whisper turns into a sonnet of love 🌹",
    "You are the light that guides me home when life feels lost 🏡",
    "If my heart had a voice, it would sing only of you 🎶",
    "You are the poem I never knew I was capable of writing ✍️",
    "In the silence between breaths, I find you waiting there 🌬️",
    "To be with you is to dance among the stars, weightless and free ✨",
    "Our souls are two verses in a poem that rhyme perfectly ❤️",
    "My love for you is the story I’ll tell the stars each night 🌌",

    // More Romantic Verses
    "Your love is my compass, guiding me through the unknown 🌍",
    "If my soul had a home, it would be the warmth of your embrace 🏠",
    "With you, my heart is a garden in eternal spring 🌷",
    "In the symphony of my life, you are the sweetest melody 🎻",
    "You are the chapter I never want to end, the story I'll never tire of reading 📖",
    "Your love is the breath that fills my chest, my every inhale and exhale 🌬️",
    "In the song of the universe, you are my harmony 🌌",
    "To love you is to touch a piece of heaven here on earth ✨",
    "Every heartbeat, a note in the symphony of my love for you 🎼",
    "In you, I found my forever, my always, my everything 💞"
];
function showLoveNote() {
    const noteElement = document.getElementById("note");

    // Generate a random love note
    const randomIndex = Math.floor(Math.random() * loveNotes.length);
    const message = loveNotes[randomIndex];

    // Reset the text content
    noteElement.textContent = "";

    let charIndex = 0;

    // Typewriter function
    function typeCharacter() {
        if (charIndex < message.length) {
            noteElement.textContent += message[charIndex];
            charIndex++;
            setTimeout(typeCharacter, 100); // Adjust speed here
        }
    }
    typeCharacter();
}

